---
- hosts: all
  tasks:
    - name: insert ssh keys
      authorized_key:
        user: root
        exclusive: no
        key: "{{ lookup('file', item) }}"
        with_items:
            - '~/.ssh/id_rsa.pub'
