---
- hosts: all
  tasks:
    - include_vars:
        file: users.yml
        name: users

    - name: set saner SSH configuration security defaults
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin no"
        - regexp: "^PermitEmptyPasswords"
          line: "PermitEmptyPasswords no"
        - regexp: "^X11Forwarding"
          line: "X11Forwarding no"
        #- regexp: "^Port"
        #  line: "Port {{ security_ssh_port }}"
        #- regexp: "^UseDNS"
        #  line: "UseDNS {{ security_ssh_usedns }}"
        #- regexp: "^ChallengeResponseAuthentication"
        #  line: "ChallengeResponseAuthentication {{ security_ssh_challenge_response_auth }}"
        #- regexp: "^GSSAPIAuthentication"
        #  line: "GSSAPIAuthentication {{ security_ssh_gss_api_authentication }}"
      notify: restart ssh
      become: yes

    - name: install Docker
      include_role:
        name: geerlingguy.docker
        apply:
          become:
            yes
      vars:
        docker_users: "{{ users | dict2items | map(attribute='key') | list }}"
        docker_package_state: latest

    - name: install python pip
      package: name=python-pip state=latest
      become: yes

    - name: install python setuptools
      pip:
        name:
          - setuptools
        state: latest
      become: yes

    - name: install docker-py
      pip:
        name:
          - docker
        state: latest
      become: yes

  handlers:
    - name: restart ssh
      service: name=ssh state=reloaded

